headers = {
    'Accept': '*/*',
    'Accept-Language': 'en-US',
    "Bnc-Location": "",
    "Bnc-Uuid": "",
    'Clienttype': "web",
    'Content-Type': 'application/json',
    'Csrftoken': 'd41d8cd98f00b204e9800998ecf8427e',
    'Device-Info': "",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
    "Priority": "u=1, i",
    "Fvideo-Id": "330a0c10361aac50ad025725adfc172d3af2489a",
    "Fvideo-Token": "",
    "Lang": "en",
    'Origin': 'https://www.binance.com',
    'Referer': 'https://www.binance.com/vi/game/tg/moon-bix',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36',
    "X-Growth-Token": ""
}